name:                nri-customers
version:             0.1.0.0
github:              "githubuser/nri-customers"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

default-extensions:
  - OverloadedStrings

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/nri-customers#readme>

dependencies:
- base >= 4.7 && < 5
- process == 1.6.4.0
- persistent == 2.9.0
- persistent-postgresql == 2.9.0
- http-conduit == 2.3.4
- katip == 0.7.0.0
- monad-logger == 0.3.30
- safe == 0.3.17
- text == 1.2.3.1
- servant == 0.15
- servant-server == 0.15
- wai == 3.2.1.2
- wai-extra == 3.0.24.3
- warp == 3.2.25
- aeson == 1.4.2.0
- transformers == 0.5.6.2
- mtl == 2.2.2
- containers == 0.6.0.1
- fast-logger == 2.4.12
- persistent-template == 2.5.4
- req == 1.2.1
- hspec == 2.6.0
- exceptions == 0.10.0
- bytestring == 0.10.8.2
- vector == 0.12.0.2
- time == 1.8.0.2

library:
  source-dirs: src

executables:
  nri-customers-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nri-customers

tests:
  nri-customers-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nri-customers
